// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package database

import (
	"database/sql"
	"time"
)

type AdminUser struct {
	ID             int32  `json:"id"`
	Username       string `json:"username"`
	Password       string `json:"password"`
	Email          string `json:"email"`
	RoleID         int32  `json:"role_id"`
	OrganizationID int32  `json:"organization_id"`
}

type Event struct {
	ID                int32         `json:"id"`
	Tag               string        `json:"tag"`
	Name              string        `json:"name"`
	Available         int32         `json:"available"`
	Capacity          int32         `json:"capacity"`
	Status            sql.NullInt32 `json:"status"`
	Frontends         string        `json:"frontends"`
	Exercises         string        `json:"exercises"`
	StartedAt         time.Time     `json:"started_at"`
	FinishExpected    time.Time     `json:"finish_expected"`
	FinishedAt        time.Time     `json:"finished_at"`
	Createdby         string        `json:"createdby"`
	Onlyvpn           sql.NullInt32 `json:"onlyvpn"`
	Secretkey         string        `json:"secretkey"`
	Disabledexercises string        `json:"disabledexercises"`
}

type ExerciseDb struct {
	ID             int32  `json:"id"`
	Name           string `json:"name"`
	OrganizationID int32  `json:"organization_id"`
	Url            string `json:"url"`
	SignKey        string `json:"sign_key"`
	AuthKey        string `json:"auth_key"`
}

type Frontend struct {
	ID       int32         `json:"id"`
	Name     string        `json:"name"`
	Image    string        `json:"image"`
	Memorymb sql.NullInt32 `json:"memorymb"`
}

type HaaukinsAgent struct {
	ID      int32  `json:"id"`
	Name    string `json:"name"`
	Url     string `json:"url"`
	SignKey string `json:"sign_key"`
	AuthKey string `json:"auth_key"`
}

type Organization struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Profile struct {
	ID             int32  `json:"id"`
	Name           string `json:"name"`
	Secret         bool   `json:"secret"`
	OrganizationID int32  `json:"organization_id"`
	Challenges     string `json:"challenges"`
}

type Role struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	WriteAll   bool   `json:"write_all"`
	ReadAll    bool   `json:"read_all"`
	WriteLocal bool   `json:"write_local"`
	ReadLocal  bool   `json:"read_local"`
}

type Team struct {
	ID               int32     `json:"id"`
	Tag              string    `json:"tag"`
	EventID          int32     `json:"event_id"`
	Email            string    `json:"email"`
	Name             string    `json:"name"`
	Password         string    `json:"password"`
	CreatedAt        time.Time `json:"created_at"`
	LastAccess       time.Time `json:"last_access"`
	SolvedChallenges string    `json:"solved_challenges"`
}
