// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package database

import (
	"database/sql"
)

type Event struct {
	ID                int32          `json:"id"`
	Tag               sql.NullString `json:"tag"`
	Name              sql.NullString `json:"name"`
	Available         sql.NullInt32  `json:"available"`
	Capacity          sql.NullInt32  `json:"capacity"`
	Status            sql.NullInt32  `json:"status"`
	Frontends         sql.NullString `json:"frontends"`
	Exercises         sql.NullString `json:"exercises"`
	StartedAt         sql.NullTime   `json:"started_at"`
	FinishExpected    sql.NullTime   `json:"finish_expected"`
	FinishedAt        sql.NullTime   `json:"finished_at"`
	Createdby         sql.NullString `json:"createdby"`
	Onlyvpn           sql.NullInt32  `json:"onlyvpn"`
	Secretkey         sql.NullString `json:"secretkey"`
	Disabledexercises sql.NullString `json:"disabledexercises"`
}

type Profile struct {
	ID         int32          `json:"id"`
	Name       sql.NullString `json:"name"`
	Secret     sql.NullBool   `json:"secret"`
	Challenges sql.NullString `json:"challenges"`
}

type Team struct {
	ID               int32          `json:"id"`
	Tag              interface{}    `json:"tag"`
	EventID          sql.NullInt32  `json:"event_id"`
	Email            sql.NullString `json:"email"`
	Name             sql.NullString `json:"name"`
	Password         sql.NullString `json:"password"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	LastAccess       sql.NullTime   `json:"last_access"`
	SolvedChallenges sql.NullString `json:"solved_challenges"`
}
