// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package database

import (
	"database/sql"
	"time"
)

type AdminUser struct {
	ID           int32  `json:"id"`
	Username     string `json:"username"`
	Password     string `json:"password"`
	FullName     string `json:"full_name"`
	Email        string `json:"email"`
	Role         string `json:"role"`
	Organization string `json:"organization"`
}

type Event struct {
	ID                int32         `json:"id"`
	Tag               string        `json:"tag"`
	Name              string        `json:"name"`
	Available         int32         `json:"available"`
	Capacity          int32         `json:"capacity"`
	Status            sql.NullInt32 `json:"status"`
	Frontends         string        `json:"frontends"`
	Exercises         string        `json:"exercises"`
	StartedAt         time.Time     `json:"started_at"`
	FinishExpected    time.Time     `json:"finish_expected"`
	FinishedAt        time.Time     `json:"finished_at"`
	Createdby         string        `json:"createdby"`
	Onlyvpn           sql.NullInt32 `json:"onlyvpn"`
	Secretkey         string        `json:"secretkey"`
	Disabledexercises string        `json:"disabledexercises"`
}

type ExerciseDb struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	Organization string `json:"organization"`
	Url          string `json:"url"`
	SignKey      string `json:"sign_key"`
	AuthKey      string `json:"auth_key"`
}

type Frontend struct {
	ID       int32         `json:"id"`
	Name     string        `json:"name"`
	Image    string        `json:"image"`
	Memorymb sql.NullInt32 `json:"memorymb"`
}

type HaaukinsAgent struct {
	ID      int32  `json:"id"`
	Name    string `json:"name"`
	Url     string `json:"url"`
	SignKey string `json:"sign_key"`
	AuthKey string `json:"auth_key"`
}

type Organization struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	OwnerUser  string `json:"owner_user"`
	OwnerEmail string `json:"owner_email"`
}

type Profile struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	Secret       bool   `json:"secret"`
	Organization string `json:"organization"`
	Challenges   string `json:"challenges"`
}

type Team struct {
	ID               int32     `json:"id"`
	Tag              string    `json:"tag"`
	EventID          int32     `json:"event_id"`
	Email            string    `json:"email"`
	Name             string    `json:"name"`
	Password         string    `json:"password"`
	CreatedAt        time.Time `json:"created_at"`
	LastAccess       time.Time `json:"last_access"`
	SolvedChallenges string    `json:"solved_challenges"`
}
