version: '3.1'
services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./.data:/var/lib/postgresql/data
      - ./.logs:/logs
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh