host: localhost
port: 8080
listening-ip: "127.0.0.1"
state-path: /path/to/state/dir

lab-expiry-duration: 1 # In minutes
lab-expiry-extension: 1 # In minutes
eventRetention: 30 #Amount of days before stopped events are removed including teams related to that event

auditLog: 
  directory: /path/to/log/dir
  fileName: AuditLog.log
  max-backups: 10
  max-size: 10
  max-age: 30

db-config:
  host: 127.0.0.1
  port: 5432
  db_name: haaukins
  username: haaukins
  password: haaukins
  

exercise-service:
  grpc: localhost
  sign-key: dev-sign-key
  auth-key: dev-auth-key
  tls-enabled: false
  

jwtSecret: test

test-delay:
  enabled: true/false
  delay-seconds: 10