host: localhost
port: 8080

db-config:
  host: 127.0.0.1
  port: 5432
  db_name: haaukins
  username: haaukins
  password: haaukins

auditlog:
  - directory: /path/to/logs/dir
  - fileName: auditlog.log
  - max-backups: 10
  - max-size: 10
  - max-age: 30

jwtSecret: test