host: localhost
port: 8080

auditLog: 
  directory: /path/to/log/dir
  fileName: AuditLog.log
  max-backups: 10
  max-size: 10
  max-age: 30

db-config:
  host: 127.0.0.1
  port: 5432
  db_name: haaukins
  username: haaukins
  password: haaukins
  eventRetention: 30 #Amount of days before stopped events are removed including teams related to that event

exercise-service:
  grpc: localhost
  sign-key: dev-sign-key
  auth-key: dev-auth-key
  tls-enabled: false
  

jwtSecret: test